% u_z_t=0
number_of_eq=number_of_eq+1;
Mat_PW(number_of_eq,dof_medium_2(1))=SV_2(3,1)*exp(-1j*k_z_2(1)*multilayer(i_interface+1).d);
Mat_PW(number_of_eq,dof_medium_2(2))=SV_2(3,2)*exp(-1j*k_z_2(2)*multilayer(i_interface+1).d);
Mat_PW(number_of_eq,dof_medium_2(3))=SV_2(3,3)*exp(-1j*k_z_2(3)*multilayer(i_interface+1).d);
Mat_PW(number_of_eq,dof_medium_2(4))=SV_2(3,4);
Mat_PW(number_of_eq,dof_medium_2(5))=SV_2(3,5);
Mat_PW(number_of_eq,dof_medium_2(6))=SV_2(3,6);
% u_z_s=0
number_of_eq=number_of_eq+1;
Mat_PW(number_of_eq,dof_medium_2(1))=SV_2(2,1)*exp(-1j*k_z_2(1)*multilayer(i_interface+1).d);
Mat_PW(number_of_eq,dof_medium_2(2))=SV_2(2,2)*exp(-1j*k_z_2(2)*multilayer(i_interface+1).d);
Mat_PW(number_of_eq,dof_medium_2(3))=SV_2(2,3)*exp(-1j*k_z_2(3)*multilayer(i_interface+1).d);
Mat_PW(number_of_eq,dof_medium_2(4))=SV_2(2,4);
Mat_PW(number_of_eq,dof_medium_2(5))=SV_2(2,5);
Mat_PW(number_of_eq,dof_medium_2(6))=SV_2(2,6);

% u_x_s=0
number_of_eq=number_of_eq+1;
Mat_PW(number_of_eq,dof_medium_2(1))=SV_2(6,1)*exp(-1j*k_z_2(1)*multilayer(i_interface+1).d);
Mat_PW(number_of_eq,dof_medium_2(2))=SV_2(6,2)*exp(-1j*k_z_2(2)*multilayer(i_interface+1).d);
Mat_PW(number_of_eq,dof_medium_2(3))=SV_2(6,3)*exp(-1j*k_z_2(3)*multilayer(i_interface+1).d);
Mat_PW(number_of_eq,dof_medium_2(4))=SV_2(6,4);
Mat_PW(number_of_eq,dof_medium_2(5))=SV_2(6,5);
Mat_PW(number_of_eq,dof_medium_2(6))=SV_2(6,6);